apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadataName }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{.Values.appLabel}}
    spec:
      containers:
        - image: "{{.Values.image.registry}}/busybox:{{.Values.image.tag}}"
          name: {{.Values.metadataName}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          command:
            - sleep
            - "3600"
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
